### ISSUE TITLE
codernate out-of-date

### ISSUE THREAD

**Issue by Dejniel** [CoderNate/CSharpToPython#1]
"Binary expression kind AsExpression not implemented yet."
It is implemented but test fail https://github.com/CoderNate/CSharpToPython/runs/117719059

**Comment by CoderNate** [comment]
It turns out I had a commit still sitting around on my hard drive that I had never pushed which fixes the issue you're talking about.  I pushed that up so the tests pass now but my build pipeline isn't cooperating.  The Uno Wasm version it was using doesn't seem to be available anymore and newer versions are giving compile errors.

**Comment by CoderNate** [comment]
I fixed the build and redeployed so I'll close this.  Thanks.
